openapi: 3.0.2
info:
  title: API Documentation
  version: Alpha
tags:
  - name: Dataset
  - name: SQL Query
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:
    datasetUuid:
      name: uuid
      in: path
      description: A dataset uuid
      required: true
      schema:
        type: string
      example: 11111111-1111-4111-1111-111111111111
    property:
      name: property
      in: path
      description: Property of a dataset
      required: true
      schema:
        type: string
      example: keyword
    propertyUuid:
      name: uuid
      in: path
      description: A property uuid
      required: true
      schema:
        type: string
      example: PROPERTY-UUID
    query:
      name: query
      in: path
      description: SQL query
      required: true
      schema:
        type: string
      example: '[SELECT * FROM DATASTORE-UUID];'
    datastoreUuid:
      name: uuid
      in: path
      description: A datastore uuid
      required: true
      schema:
        type: string
      example: DATASTORE-UUID
    harvestId:
      name: id
      in: path
      description: A harvest identifier
      required: true
      schema:
        type: string
      example: HARVEST-ID
    harvestRunId:
      name: run_id
      in: path
      description: A harvest run identifier
      required: true
      schema:
        type: string
      example: HARVEST-RUN-ID
  schemas:
    # @TODO: Load directly from dkan2's schema/collections/dataset.json schema
    Dataset:
      type: object
      required:
        - title
        - description
        - identifier
        - accessLevel
      properties:
        title:
          type: string
        description:
          type: string
        identifier:
          type: string
        accessLevel:
          type: string
          enum:
            - public
            - restricted public
            - non-public
paths:
  /api/v1/dataset:
    get:
      operationId: dataset-get-all
      summary: Get all datasets
      tags:
        - Dataset
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
    post:
      operationId: dataset-create
      summary: Create a dataset
      tags:
        - Dataset
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dataset'
            example:
              title: UPDATED Title for 111111
              description: UPDATED Description for 111111
              identifier: 11111111-1111-4111-1111-111111111111
              accessLevel: public
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                  - identifier
                properties:
                  endpoint:
                    type: string
                  identifier:
                    type: string
        '409':
          description: Resource already exists
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                properties:
                  endpoint:
                    type: string
        '401':
          description: Unauthorized
  /api/v1/dataset/{uuid}:
    get:
      operationId: dataset-get
      summary: Get this dataset
      tags:
        - Dataset
      parameters:
        - name: uuid
          in: path
          description: A dataset uuid
          required: true
          schema:
            type: string
          example: c9e2d352-e24c-4051-9158-f48127aa5692
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
    put:
      operationId: dataset-put
      summary: Replace a dataset
      tags:
        - Dataset
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/datasetUuid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dataset'
            example:
              title: UPDATED Title for 111111
              description: UPDATED Description for 111111
              identifier: 11111111-1111-4111-1111-111111111111
              accessLevel: public
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                  - identifier
                properties:
                  endpoint:
                    type: string
                  identifier:
                    type: string
        '401':
          description: Unauthorized
    patch:
      operationId: dataset-patch
      summary: Update a dataset
      tags:
        - Dataset
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/datasetUuid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              # Only a subset of Dataset schema
              type: object
            example:
              theme:
                - Some New Theme
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                  - identifier
                properties:
                  endpoint:
                    type: string
                  identifier:
                    type: string
        '401':
          description: Unauthorized
    delete:
      operationId: dataset-delete
      summary: Delete a dataset
      tags:
        - Dataset
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/datasetUuid'
      responses:
        '200':
          description: Dataset has been deleted
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized
  /api/v1/dataset/{uuid}/resources:
    get:
      operationId: dataset-get-resources
      summary: Get a dataset's resources
      tags:
        - Dataset
      parameters:
        - name: uuid
          in: path
          description: A dataset uuid
          required: true
          schema:
            type: string
          example: c9e2d352-e24c-4051-9158-f48127aa5692
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - identifier
                    - data
                  properties:
                    identifier:
                      type: string
                    data:
                      type: object
  /api/v1/{property}:
    get:
      operationId: property-get-all
      summary: Get properties
      tags:
        - Properties
      parameters:
        - $ref: '#/components/parameters/property'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - identifier
                  properties:
                    identifier:
                      type: string
  /api/v1/{property}/{uuid}:
    get:
      operationId: property-get
      summary: Get a property
      tags:
        - Properties
      parameters:
        - $ref: '#/components/parameters/property'
        - $ref: '#/components/parameters/propertyUuid'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - identifier
                properties:
                  identifier:
                    type: string
    put:
      operationId: property-put
      summary: Replace a property
      tags:
        - Properties
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/property'
        - $ref: '#/components/parameters/propertyUuid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - identifier
              properties:
                identifier:
                  type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                  - identifier
                properties:
                  endpoint:
                    type: string
                  identifier:
                    type: string
        '401':
          description: Unauthorized
    patch:
      operationId: property-patch
      summary: Update a property
      tags:
        - Properties
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/property'
        - $ref: '#/components/parameters/propertyUuid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              # Only a subset of Property schema
              type: object
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                  - identifier
                properties:
                  endpoint:
                    type: string
                  identifier:
                    type: string
        '401':
          description: Unauthorized
  /api/v1/sql/{query}:
    get:
      operationId: datastore-query
      summary: Query resources in datastore
      description: >
        Interact with resources in the datastore using an SQL-like syntax.
      tags:
        - SQL Query
      parameters:
        - $ref: '#/components/parameters/query'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /api/v1/harvest:
    get:
      operationId: harvest-get-all
      summary: Lists harvest identifiers
      description: >
        Lists the identifiers of all registered harvests.
      tags:
        - Harvest
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      operationId: harvest-register
      summary: Register a new harvest
      description: >
        Registers a new harvest, after validating against our schema.
      tags:
        - Harvest
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                  - identifier
                properties:
                  endpoint:
                    type: string
                  identifier:
                    type: string
  /api/v1/harvest/info/{id}:
    get:
      operationId: harvest-info
      summary: List previous runs for a harvest id
      description: >
        Lists the identifiers (timestamps) of previous runs for a particular
        harvest id.
      tags:
        - Harvest
      parameters:
        - $ref: '#/components/parameters/harvestId'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /api/v1/harvest/info/{id}/{run_id}:
    get:
      operationId: harvest-run-info
      summary: Information about a specific previous harvest run
      description: >
        Gives information about a previous run for a specific harvest run.
      tags:
        - Harvest
      parameters:
        - $ref: '#/components/parameters/harvestId'
        - $ref: '#/components/parameters/harvestRunId'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
  /api/v1/harvest/run/{id}:
    put:
      operationId: harvest-run
      summary: Runs a harvest
      description: >
        Runs a harvest for a specific identifier.
      tags:
        - Harvest
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/harvestId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                  - identifier
                  - result
                properties:
                  endpoint:
                    type: string
                  identifier:
                    type: string
                  result:
                    type: string
  /api/v1/datastore/{uuid}:
    get:
      operationId: datastore-get
      summary: Datastore statistics
      description: >
        Returns the numbers of rows and columns, and a list of columns headers
        from the datastore.
      tags:
        - Datastore
      parameters:
        - $ref: '#/components/parameters/datastoreUuid'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - numOfRows
                  - numOfColumns
                  - columns
                properties:
                  numOfRows:
                    type: integer
                  numOfColumns:
                    type: integer
                  columns:
                    type: array
                    items:
                      type: string
    delete:
      operationId: datastore-delete
      summary: Delete a datastore
      description: >
        Delete one or more datastores. If the uuid parameter is that of
        a resource, delete that resource. If the uuid parameter is that of
        a dataset, delete all resources of that dataset.
      tags:
        - Datastore
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/datastoreUuid'
      responses:
        '200':
          description: Dataset has been deleted
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
  /api/v1/datastore/import/{uuid}:
    put:
      operationId: datastore-import
      summary: Datastore import
      description: >
        Immediately starts the import process for a datastore.
      tags:
        - Datastore
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/datastoreUuid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                  - identifier
                properties:
                  endpoint:
                    type: string
                  identifier:
                    type: string
  /api/v1/datastore/import/{uuid}/deferred:
    put:
      operationId: datastore-deferred-import
      summary: Deferred datastore import
      description: >
        Queues the process of importing a resource to the datastore.
      tags:
        - Datastore
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/datastoreUuid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - endpoint
                  - identifier
                properties:
                  endpoint:
                    type: string
                  identifier:
                    type: string
  /api/v1/docs:
    get:
      operationId: docs-get
      summary: Complete json documentation
      tags:
        - Documentation
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
  /api/v1/docs/{uuid}:
    get:
      operationId: docs-get-dataset-specific
      summary: Dataset-specific json documentation
      tags:
        - Documentation
      parameters:
        - name: uuid
          in: path
          description: A dataset uuid
          required: true
          schema:
            type: string
          example: c9e2d352-e24c-4051-9158-f48127aa5692
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
