language: php
sudo: false

php:
  - 5.5

mysql:
  database: dkan_travis
  username: root
  encoding: utf8

addons:
  artifacts:
    debug: true
    paths:
      - ./screens
    target_paths: $TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    bucket: nucivic-travis-artifacts
    s3_region: us-east-1

install:
  - cd test
  - composer install
  - mysql -e 'create database dkan_travis;'

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:dev-master
  - composer global require --no-interaction youngj/httpserver:*

before_script:
  # Install DKAN
  - cd ../..
  - mkdir drupal
  - cd drupal
  - cp $TRAVIS_BUILD_DIR/drupal-org-core.make ./
  - drush make --prepare-install drupal-org-core.make --yes
  - cp -R $TRAVIS_BUILD_DIR profiles/
  - cd profiles/dkan
  - drush -y make --no-core --contrib-destination=./ drupal-org.make --no-recursion
  - cd $TRAVIS_BUILD_DIR/test
  - mv ../../drupal ./
  - cd drupal
  - drush si dkan --sites-subdir=default --db-url=mysql://root:@127.0.0.1:3306/dkan_travis --account-name=admin --account-pass=admin  --site-name="DKAN" install_configure_form.update_status_module='array(FALSE,FALSE)' --yes
  - drush cc all --yes
  - drush cc drush
  - drush --quiet --yes --root=$PWD runserver :8888 > /dev/null 2>&1 &
  - sleep 4

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

  - cd ..
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - java -jar selenium-server-standalone-2.42.2.jar -quiet -p 4444 -log shut_up_selenium &
  - sleep 5

script:
  - bash features-tests.sh $TRAVIS_BUILD_DIR
  - bin/behat features/administrator.feature
  - bin/behat features/panels.feature
  - bin/behat features/groups.feature
  - bin/behat features/dataset.feature
  - bin/behat features/datastore.feature
  - bin/behat features/editor.feature
  - bin/behat features/home.feature
  - bin/behat features/search.feature
  - bin/behat features/recline.feature
  - bin/behat features/widgets.feature
  - bin/behat features/data_dashboard.feature
  - bin/behat features/dkan_data_story_ui.feature
  - bin/behat features/role_storyteller.feature

notifications:
  slack:
    rooms:
      - nucivic:t3p2KxXdzymmwxitWPvfAsnK#monitor-devops
      - nucivic:t3p2KxXdzymmwxitWPvfAsnK#monitor-dkan
      - nucivic:t3p2KxXdzymmwxitWPvfAsnK#monitor-data-starter
