language: php

php:
  - 5.3

mysql:
  database: dkan_dataset_test
  username: root
  encoding: utf8

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # install drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.8.0
  - phpenv rehash

  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database dkan_dataset_test'
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/dkan_dataset_test --enable=simpletest dkan_dataset_test

  # copy drupal
  - git clone --branch 7.x-1.x https://github.com/nuams/dkan_dataset.git

  # reference and enable travis_ci_drupal_module_example in build site
  - cp -r dkan_dataset dkan_dataset_test/drupal/sites/all/modules/dkan_dataset
  - cd dkan_dataset_test/drupal
  - drush make -v --no-core --yes sites/all/modules/dkan_dataset/dkan_dataset.make
  - drush --yes pm-enable dkan_dataset

  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script: drush test-run --xml 'DKAN Dataset' --uri=http://127.0.0.1:8080
