name: Project Open Data Light
description: Project Open Data based schema that trims some of the POD fat.
api: 1
primaryCollection: dataset
collections:
  - dataset
  - organization
  - keyword
  - license
  - theme
references:
  dataset:
      keyword: keyword
      license: license
      theme: theme
      publisher: organization
collectionToBundleMap:
  publisher: organization
  dataset: dataset
  keyword: keyword
  theme: theme
  license: license
collectionToEntityMap:
  dataset: node
  organization: node
  publisher: node
  publisher: node
  keyword: taxonomy_term
  theme: taxonomy_term
  license: taxonomy_term
facets:
  keyword:
    label: Tags
    field: keyword.title
  theme:
    label: Category
    field: theme.title
  publisher:
    label: Organization
    field: publisher.name
  distribution:
    label: Format
    field: dataset.distribution.format
